### ISSUE TITLE
Error message when compiling

### ISSUE THREAD

**Issue by bantik78** [ecasti-gmail-com/m5gps#2]
Sorry, I've pushed the wrong button

**Comment by bantik78** [comment]
![error](https://user-images.githubusercontent.com/98657292/151669046-b271bfc1-e6a5-457c-ad5a-89ab9d7eee9f.jpg)

**Comment by bantik78** [comment]
I think, thats why you write first "char stringa..., and when you want to care this variable as a string ?
![error 2](https://user-images.githubusercontent.com/98657292/151669219-4f572fdc-8859-4644-a161-6ef70cedec07.jpg)
!

**Comment by ecasti-gmail-com** [comment]
Thanks for reporting,
I think I got the problem in the message before the failing.
_cc1plus.exe some warnings being treated as errors_ 
Never tested on Windows, but looks like  ccplus consider this conversion a warning and trow the error
Have a look also on https://github.com/Links2004/arduinoWebSockets/issues/319 
Let me know if changing the preference fix the issue.

**Comment by bantik78** [comment]
Hello Enrico,

yes, this solution helped to compile. But the GPS-Tracker doesn't start, the screen is black. Could this failure be according to no gps module is connected?

**Comment by ecasti-gmail-com** [comment]
Yes, 
it's required to have a GPS connected on Port C (pins 16,17 on M5stack Grey Core).
I have a mock that can be used for testing without a GPS, later will make public.
For the sake tracking the compiler problem, I will close this issue.
You can still reach out to me via messages on Hackster or Facebook
